spring.application.name=Infrastructure
server.port=8085

# Message Producer
crosswords.catalog.message.topic = list-messageModel-topic
crosswords.api.path.message =/messageucolab/v1/messages/findbyapplication
crosswords.api.path.message.findByCode =/messageucolab/v1/messages/findbycode

# MongoDB connection properties
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.host=${MONGODB_HOST}
spring.data.mongodb.port=${MONGODB_PORT}
spring.data.mongodb.username=${MONGODB_USER}
spring.data.mongodb.password=${MONGODB_PASSWORD}
spring.data.mongodb.database=${MONGODB_DATABASE}
    
#Redis cache
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DATABASE}

spring.config.import=classpath:secret.properties

# Prometheus
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.http.client.requests=true
