spring.application.name=Infrastructure
server.port=8085

# Azure Configuration
spring.cloud.azure.credential.client-id=${AZURE_CLIENT_ID}
spring.cloud.azure.credential.client-secret=${AZURE_CLIENT_SECRET}
spring.cloud.azure.profile.tenant-id=${AZURE_TENANT_ID}

spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=${AZURE_KEYVAULT_UCOLAB_ENDPOINT}
spring.cloud.azure.keyvault.secret.enabled=true

# API Configuration
crosswords.api.path.message=/messageucolab/v1/application
crosswords.api.path.token.application =/{id}/token
crosswords.api.path.message.environment =/environment
crosswords.api.path.message.code.environment =/code/{messageCode}

# MongoDB connection properties
spring.data.mongodb.uri=${MONGOURI}
spring.data.mongodb.host=${MONGODBHOST}
spring.data.mongodb.port=${MONGODBPORT}
spring.data.mongodb.username=${MONGODBUSER}
spring.data.mongodb.password=${MONGODBPASSWORD}
spring.data.mongodb.database=${MONGODBDATABASE}
    
# Redis cache
spring.data.redis.host=${REDISHOST}
spring.data.redis.port=${REDISPORT}
spring.data.redis.password=${REDISPASSWORD}
spring.data.redis.database=${REDISDATABASE}

# Prometheus
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.http.client.requests=true

# Doppler Configuration
doppler.token=${DOPPLERTOKEN}
doppler.request={"project":"ucolab","config":"dev","change_requests":[{"name":"%s","originalName":"%s","value":"%s"}]}
doppler.url-config-secrets-post=https://api.doppler.com/v3/configs/config/secrets
doppler.url-config-secrets-get=https://api.doppler.com/v3/configs/config/secret?project=ucolab&config=dev&name=%s

# Postgres Configuration
datasource.url=jdbc:postgresql://${POSTGRESHOST}:${POSTGRESPORT}/${POSTGRESDATABASE}
datasource.username=${POSTGRESUSERNAME}
datasource.password=${POSTGRESPASSWORD}
datasource.dialect=org.hibernate.dialect.PostgreSQLDialect
datasource.show-sql=true

# Pulsar Configuration
pulsar.service-url=${PULSARURL}
pulsar.topic-name=${PULSARTOPICNAME}