spring.application.name=Infrastructure
server.port=8085

# Azure Configuration
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=${AZURE_KEYVAULT_UCOLAB_ENDPOINT}

# Message Producer
crosswords.catalog.message.topic = list-messageModel-topic
crosswords.api.path.message=/messageucolab/v1/messages
crosswords.api.apth.message.application.code =/application/{id}/message/{messageCode}
crosswords.api.apth.message.application =/application/{id}/messages
crosswords.api.path.token.application = /application/{id}/token

# MongoDB connection properties
spring.data.mongodb.uri=${MONGOURI}
spring.data.mongodb.host=${MONGODBHOST}
spring.data.mongodb.port=${MONGODBPORT}
spring.data.mongodb.username=${MONGODBUSER}
spring.data.mongodb.password=${MONGOPASSWORD}
spring.data.mongodb.database=${MONGODBDATABASE}
    
#Redis cache
spring.data.redis.host=${REDISHOST}
spring.data.redis.port=${REDISPORT}
spring.data.redis.password=${REDISPASSWORD}
spring.data.redis.database=${REDISDATABASE}

spring.config.import=classpath:secret.properties

# Prometheus
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.http.client.requests=true

# Doppler Configuration
doppler.token=${DOPPLERTOKEN}

# Postgres Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ucolab
spring.datasource.username=crosswords
spring.datasource.password=crosswords
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect