# AZURE_KEYVAULT_UCOLAB_ENDPOINT: La URL del endpoint del Azure Key Vault donde se almacenan los secretos.
# Asegura la gesti?n centralizada y segura de claves, secretos y certificados.
AZURE_KEYVAULT_UCOLAB_ENDPOINT= https://mi-vault-seguro.vault.azure.net/

# DOPPLERTOKEN: El token de acceso a Doppler, una herramienta de gesti?n de secretos.
# Este token se utiliza para autenticarse y recuperar configuraciones seguras.
DOPPLERTOKEN= dp.token_doppler

# PULSARURL: La URL del broker de Apache Pulsar que actúa como sistema de mensajería.
# Se utiliza para publicar y consumir mensajes dentro de un sistema distribuido.
PULSARURL=pulsar://pulsar-standalone:6650

# PULSARTOPICNAME: El nombre del tópico (topic) de Apache Pulsar donde se publicarán o consumirán los mensajes.
# Este tópico organiza los mensajes por canal lógico dentro del sistema de mensajería.
PULSARTOPICNAME=crossword-topic