# MongoDB Configuración
# MONGOURI: La URI de conexión a la base de datos MongoDB.
# Formato: mongodb://<usuario>:<contraseña>@<host>:<puerto>/<nombre_de_la_base_de_datos>?<opciones>
# Ejemplo: mongodb://password:password@localhost:27017/mi_base_de_datos
MONGOURI: mongodb://usuario:password@localhost:27017/mi_base_de_datos

# MONGOPASSWORD: La contraseña del usuario de MongoDB.
MONGOPASSWORD: password

# MONGODBHOST: El host de la base de datos MongoDB.
MONGODBHOST: localhost

# MONGODBUSER: El usuario de la base de datos MongoDB.
MONGODBUSER: usuario

# MONGODBPORT: El puerto de conexión a la base de datos MongoDB.
# Por defecto, MongoDB utiliza el puerto 27017.
MONGODBPORT: 27017

# MONGODBDATABASE: El nombre de la base de datos en MongoDB.
MONGODBDATABASE: mi_base_de_datos

# Redis Configuration
# REDISPASSWORD: La contraseña para conectarse a Redis.
REDISPASSWORD: contraseña_redis

# REDISPORT: El puerto de conexión a Redis.
# Por defecto, Redis utiliza el puerto 6379.
REDISPORT: 6379

# REDISHOST: El host de Redis.
REDISHOST: localhost

# REDIS_DATABASE: El número de la base de datos en Redis.
# Redis permite múltiples bases de datos numeradas, por defecto es 0.
REDISDATABASE: 0

# POSTGRES_HOST: El host del servidor de la base de datos PostgreSQL.
POSTGRESHOST: localhost

# POSTGRES_PORT: El puerto de conexión a la base de datos PostgreSQL.
# Por defecto, PostgreSQL utiliza el puerto 5432. Aquí se ha definido el puerto 5435.
POSTGRESPORT: 5435

# POSTGRES_DATABASE: El nombre de la base de datos PostgreSQL.
POSTGRESDATABASE: base_de_datos_escritura

# POSTGRES_USERNAME: El nombre de usuario para conectarse a PostgreSQL.
POSTGRESUSERNAME: postgres

# POSTGRES_PASSWORD: La contraseña del usuario de PostgreSQL.
POSTGRESPASSWORD: postgres


# AZURE_KEYVAULT_UCOLAB_ENDPOINT: La URL del endpoint del Azure Key Vault donde se almacenan los secretos.
# Asegura la gestión centralizada y segura de claves, secretos y certificados.
AZURE_KEYVAULT_UCOLAB_ENDPOINT: https://mi-vault-seguro.vault.azure.net/

# DOPPLERTOKEN: El token de acceso a Doppler, una herramienta de gestión de secretos.
# Este token se utiliza para autenticarse y recuperar configuraciones seguras.
DOPPLERTOKEN: dp.token_doppler